# Generated by Django 4.1.5 on 2023-02-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('MEL', 'Monitoring Evaluation and learning'), ('GOV_EDUC', 'Government Education'), ('GOVT_HEALTH', 'Government Health'), ('TELE', 'Teletherapy'), ('CAM', 'Communications advocacy and Management'), ('NGO', 'Non Government Organization'), ('HRA', 'Human Resource and Administration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'super_user'), (2, 'staff')]),
        ),
    ]
