# Generated by Django 4.1.5 on 2023-02-17 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('OPS', 'Operations'), ('FIN', 'Finance'), ('MEL', 'Monitoring Evaluation and learning'), ('IT', 'IT & DIGITAL PLATFORMS'), ('GOV_EDUC', 'Government Education'), ('GOVT_HEALTH', 'Government Health'), ('TELE', 'Teletherapy'), ('CPA', 'Communications Advocacy and Partnerships'), ('NGO', 'Non Government Organization'), ('HRA', 'Human Resource and Administration')], max_length=50),
        ),
        migrations.CreateModel(
            name='DepartmentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('OPS', 'Operations'), ('FIN', 'Finance'), ('MEL', 'Monitoring Evaluation and learning'), ('IT', 'IT & DIGITAL PLATFORMS'), ('GOV_EDUC', 'Government Education'), ('GOVT_HEALTH', 'Government Health'), ('TELE', 'Teletherapy'), ('CPA', 'Communications Advocacy and Partnerships'), ('NGO', 'Non Government Organization'), ('HRA', 'Human Resource and Administration')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
